# ========================== CONFIG FOR LOCKLIKE =============================
[General]
#! SystemInfo (overriden by sync script ignore)
os=Arch
host=localhost

# ============================================================================
# Clock
# ============================================================================
# 12 hours or 24 Hours true=12 [true | false]
ap=false

# ============================================================================
# WELCOME MESSAGE
# ============================================================================
# Enable welcome message [true | false]
enableWelcomeMessage=true

# Welcome message background opacity [0.0 to 1.0]
welcomeBgBlurAmount=0.7
welcomeColorOpacity=0.7
# mainCard background opacity and blur [0.0 to 2.0]
mainCardBlurAmount=0.9
mainCardColorOpacity=0.9
mainCardComponentsOpacity=0.9
# Welcome message background blur [true | false]
welcomeBgBlur=true
mainCardBgBlur=true
sessionPicker=false

# ============================================================================
# COLOR SCHEME
# ============================================================================
#! Do not touch these! (auto-synced by Caelestia)
background=#0b0f0c
mainCard=#0b0f0c
subComponents=#141b17
text=#dee8df
textDark=#e8feff
primary=#568068
onPrimary=#1e4833
secondary=#b4ccbc
onSecondary=#304538
tertiary=#e8feff
onTertiary=#2d676c
onSuccess=#213528
inverseOnSurface=#525652
surface=#0b0f0c
surfaceVariant=#1f2822
surfaceContainerLow=#0f1511
surfaceContainer=#141b17
surfaceContainerHigh=#1a211c
outline=#6e7870
error=#fa746f
