[General]
background=#12110e
mainCard=#12110e
subComponents=#1f1f19
text=#edf0e4
textDark=#e6ffe9
primary=#9b9b72
onPrimary=#61603c
secondary=#dadcc4
onSuccess=#35212d
inverseOnSurface=#585a54
outline=#7c7e74
