[General]
; Root context properties is already injected by the SDDM greeter binary so make lint ignore them
disableUnqualifiedAccess = "sddm,config,userModel,sessionModel,keyboard,screenModel"
disableHeuristic = true
