[General]
DisableDefaultImports=false
MaxWarnings=-1

[Warnings]
; Allow SDDM injected root objects without flagging them
ContextProperties=disable

AttachedPropertyReuse=disable
FunctionUsedBeforeDeclaration=disable
Quick.AttachedPropertyReuse=disable
Quick.ControlsAttachedPropertyReuse=disable
Shadow=disable
UseProperFunction=disable
Void=disable
CompilerWarnings=disable
ImportFailure=disable
ImportFileSelector=disable
LintPluginWarnings=disable
MultilineStrings=info
UnusedImports=info
UnqualifiedAccess=warning
PreferNonVarProperties=warning
VarUsedBeforeDeclaration=warning