# ======================== CONFIG FOR MINIMALISTV2 ===========================
[General]
# ============================================================================
# TYPOGRAPHY
# ============================================================================
# Font Family
fontFamily="Rubik"

# Font Size
FontSize=11

# Avatar Size
AvatarSize=120

# ============================================================================
# BORDER RADIUS (roundness)
# ============================================================================
# UI Elements (inputs, combo boxes, toast)
elementRadius=25

# Login Card
cardRadius=75

# ============================================================================
# VISUAL EFFECTS
# ============================================================================
# Card border [true | false]
cardBorder=false

# Card Opacity [0 to 1]
cardOpacity=0.35

# Card Drop shadows [true | false]
dropShadows=true

# Background blur [true | false]
blurEnabled=true

# Background blur strength [0.0 to 1.0]
blurStrength=0.5

# Background overlay opacity [0 to 1]
overlayOpacity=0.4

# ============================================================================
# DEBUG
# ============================================================================
# Debug mode (enable debug keyboard shortcuts) [true | false]
debugMode=false

# ============================================================================
# COLOR SCHEME
# ============================================================================
# Do not touch these! (auto-synced by Caelestia)
mPrimary=#a0cddf
mOnPrimary=#144654

mSecondary=#b3cad4
mOnSecondary=#2e434b

mTertiary=#cdddff
mOnTertiary=#3a4f72

mError=#fa746f
mOnError=#490006

mSurface=#0b0f11
mOnSurface=#dee7eb

mSurfaceVariant=#1e272b
mOnSurfaceVariant=#a3adb1

mSurfaceContainer=#141b1d

mOutline=#6e777b
mShadow=#000000

mHover=#a0cddf
mOnHover=#144654
